### PR TITLE
[Windows] Expand PMS install location detection

### PR DESCRIPTION
**Pull request by danrahn**
There are a few scenarios where the current logic to find the PMS install directory will fail:

* 32-bit PMS on 64-bit Windows - By default PMS will be installed to `%PROGRAMFILES(X86)%`, not `%PROGRAMFILES%`, which this script doesn't check for. Additionally, there seems to be a bug that doesn't correctly set `InstallFolder` in the registry, resulting in us looking in the wrong folder.
* `InstallPath` is written to `HKLM` instead of `HKCU` - I'm not sure what determines where the key gets saved (maybe it's new behavior surrounding the recent `InstallPath` fixes in PMS), but in one of my tests it was added to `HKLM`, but we only check `HKCU`.

This change attempts to address those issues by doing the following:
* Add an `InstallPath` check in `HKLM\Software\Plex, Inc.\Plex Media Server`
* If `InstallPath` isn't set, or the given `InstallPath` results in a path to `Plex SQLite` that doesn't exist, check `%PROGRAMFILES%`
* If it can't be found in `%PROGRAMFILES%`, look in `%PROGRAMFILES(X86)%`
  * If found in (x86), add a note that the user should probably upgrade to the 64-bit version of PMS.
* If none of the above works, ask the user to provide the full path to `Plex SQLite.exe`.

Validation:
* Standard install path:
  * 64-bit OS, 64-bit PMS - we correctly read from `%PROGRAMFILES%`
  * 64-bit OS, 32-bit PMS - we may incorrectly read from `%PROGRAMFILES%` due to an incorrect `InstallFolder`, but we then realize `%PlexSQL%` doesn't exist, so are able to successfully fall back to `"%PROGRAMFILES(X86)%\Plex\Plex Media Server\Plex SQLite.exe"`
  * 32-bit OS, 32-bit PMS - we correctly read from `%PROGRAMFILES%`
  * ARM OS, 32/64-bit PMS - same behavior as 64-bit OS.

For custom install paths, it works as expected as long as it's properly set, in `HKCU` or `HKLM`, but as mentioned above, it seems like that might not always be the case.

Fixes: #143

### CODE REVIEW

**Comment by ChuckPa** [comment]
Outstanding.   Thank you.

Might you feel like tackling another bit ?

The Plex PhotoTranscoder cache loves to collect a lot of files.
PMS is supposed to clean them up after 30 days but often doesn't due to Scheduled Tasks limitations (allotted time)

I have added this capability (Prune) to DBRepair.sh.

Would you mind taking a look at it and consider adding an issue in this Repo (Enhancement Request)
with PR  which adds the cleanup I added?

**Comment by danrahn** [comment]
> Outstanding. Thank you.
> 
> Might you feel like tackling another bit ?
> 
> The Plex PhotoTranscoder cache loves to collect a lot of files. PMS is supposed to clean them up after 30 days but often doesn't due to Scheduled Tasks limitations (allotted time)
> 
> I have added this capability (Prune) to DBRepair.sh.
> 
> Would you mind taking a look at it and consider adding an issue in this Repo (Enhancement Request) with PR which adds the cleanup I added?

I can take a look! Batch scripts definitely aren't my forte, but I'll see what I can come up with.

**Comment by ChuckPa** [comment]
How's your Powershell?

**Comment by danrahn** [comment]
> How's your Powershell?

Shaky at best. Google has been my friend for a lot of the changes I've made here, but I'm comfortable enough with Windows and Plex that things have been relatively smooth so far.

> Another user is helping with prune as well as configuration detection.
>
> This is starting to feel VERY much like we need to move to a proper collaborative effort for Windows just like exists for Linux?

Yeah, it'd be great if there was an effort to get the Windows script in-line with the Linux one. If the other user working on this is actually familiar with Powershell, I'd probably defer to them, given my lack of experience with PS mentioned above 😅

**Pull request merged**
