### PR TITLE
Support for Arch-based distributions

### PR DESCRIPTION
**Pull request by Frankkz**
Fixes: https://github.com/ChuckPa/PlexDBRepair/issues/78

### Explanation of changes; 
 - source /etc/os-release
 - is $ID "arch"
 OR
 - does $ID_LIKE contain "arch"
 - HostType="$PRETTY_NAME" to use $PRETTY_NAME from /etc/os-release

### Test using the above changes: 
`cat /etc/os-release`
```.env
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

```
2023-06-09 14.11.24 - ============================================================
2023-06-09 14.11.24 - Session start: Host is Manjaro Linux
2023-06-09 14.11.28 - Stop    - PASS
2023-06-09 14.12.54 - Auto    - START
2023-06-09 14.12.56 - Check   - Check com.plexapp.plugins.library.db - PASS
2023-06-09 14.12.57 - Check   - Check com.plexapp.plugins.library.blobs.db - PASS
2023-06-09 14.12.57 - Check   - PASS
2023-06-09 14.13.11 - Repair  - Export databases - PASS
2023-06-09 14.13.17 - Repair  - Import - PASS
2023-06-09 14.13.18 - Repair  - Verify main database - PASS (Size: 77MB/71MB).
2023-06-09 14.13.18 - Repair  - Verify blobs database - PASS (Size: 143MB/146MB).
2023-06-09 14.13.18 - Repair  - Move files - PASS
2023-06-09 14.13.18 - Repair  - PASS
2023-06-09 14.13.18 - Repair  - PASS
2023-06-09 14.13.18 - Reindex - MakeBackup com.plexapp.plugins.library.db - PASS
2023-06-09 14.13.18 - Reindex - MakeBackup com.plexapp.plugins.library.blobs.db - PASS
2023-06-09 14.13.18 - Reindex - MakeBackup - PASS
2023-06-09 14.13.19 - Reindex - Reindex: com.plexapp.plugins.library.db - PASS
2023-06-09 14.13.19 - Reindex - Reindex: com.plexapp.plugins.library.blobs.db - PASS
2023-06-09 14.13.19 - Reindex - PASS
2023-06-09 14.13.19 - Reindex - PASS
2023-06-09 14.13.19 - Auto    - COMPLETED
2023-06-09 14.13.35 - Exit    - Retain temp files.
```

Thanks!

### CODE REVIEW

**Review by ChuckPa — CHANGES_REQUESTED** [review]
1.   Variables $ID, $ID_LIKE, and $PRETTY_NAME are not defined in the confines of the script.
2.  Please  revisit how to obtain those strings.

If you wish,  I'll use this as the basis for finalizing the changes for 1.0.8

**Comment by Frankkz** [comment]
> 1. Variables $ID, $ID_LIKE, and $PRETTY_NAME are not defined in the confines of the script.
> 
>     2. Please  revisit how to obtain those strings.
> 
> 
> If you wish, I'll use this as the basis for finalizing the changes for 1.0.8

Hello, I'd be totally fine with you taking over :), I am not experienced enough with shell.

My reason for using "source /etc/os-release" is that I thought it would load the content of that file as variables, which are then able to be used.

Based on the documentation for this particular file I thought it was ok to handle it this way
> The format of os-release is a newline-separated list of environment-like shell-compatible variable assignments. It is possible to source the configuration from Bourne shell scripts, however, beyond mere variable assignments, no shell features are supported (this means variable expansion is explicitly not supported), allowing applications to read the file without implementing a shell compatible execution engine.

```shell
sh-5.1$ source /etc/os-release && echo ID: $ID; echo ID_LIKE: $ID_LIKE; echo PRETTY_NAME: $PRETTY_NAME
ID: manjaro
ID_LIKE: arch
PRETTY_NAME: Manjaro Linux
```

**Comment by ChuckPa** [comment]
This is where I'd get hit with a violation.

```
source /etc/os-release
```

That's what your change is based on.
It's  fine for private use but not for publishing software.

I will take what you show me here and use it.   I don't mind.

**Comment by ChuckPa** [comment]
On this branch:   https://github.com/ChuckPa/PlexDBRepair/tree/chuckpa/arch-linux-refinement

please find my integration of your changes into /bin/sh.

I think I've captured what you're trying to do.

I don't have a way to test and would appreciate you giving it a shot.

1.  Minimized to this:
```
  # Arch Linux (must check for native Arch after binhex)
  elif [ -e /etc/os-release ] &&  [ "$(grep '=arch' /etc/os-release)" != "" ] && \
       [ -d /usr/lib/plexmediaserver ] && \
       [ -d /var/lib/plex ]; then
```

2.  Pick up pretty name of the variants
```
HostType="$(grep PRETTY_NAME /etc/os-release | sed -e 's/^.*="//' | tr -d \" )"
```


Thoughts?

**Comment by Frankkz** [comment]
Hey, this works on my manjaro machine.
```
2023-06-09 21.26.28 - ============================================================
2023-06-09 21.26.28 - Session start: Host is Manjaro Linux
2023-06-09 21.26.51 - Exit    - Retain temp files.
```

One issue is that this would miss alternative formatting/syntax;
eg.
```.env
ID_LIKE="arch" 
```

**Comment by ChuckPa** [comment]
no it will  catch ANYTHING that ends in `=arch`  :)

**Comment by ChuckPa** [comment]
Would you try this please?

I restructured the test a bit to provide future adaptation  more readily.

**Comment by Frankkz** [comment]
```
ERROR:  Tool running as username 'user'.  'Manjaro Linux' requires 'root' user privilege.
        (e.g 'sudo -su root' or 'sudo bash')
        Exiting.
```
```
2023-06-10 14.24.15 - ============================================================
2023-06-10 14.24.15 - Session start: Host is Manjaro Linux
2023-06-10 14.24.30 - Exit    - Delete temp files.
2023-06-10 14.24.30 - Session end. za 10 jun 2023 14:24:30 CEST
2023-06-10 14.24.30 - ============================================================
```

Looks good to me!

**Comment by ChuckPa** [comment]
With my work on the branch,  I'm going to close this in favor of what you just tested.

**Pull request closed without merging**
