### PR TITLE
Add update check and download to script

### PR DESCRIPTION
**Pull request by causefx**

### CODE REVIEW

**Comment by ChuckPa** [comment]
Nice.

Request:   
1.  Don't use `0` as option.   
```  # Main menu loop
  while [ $Choice -eq 0 ]
  do
    if [ $ShowMenu -eq 1 ] && [ $Scripted -eq 0 ]; then

```

2.   Make certain target pathname `"$0"` is writable 
3.

**Comment by causefx** [comment]
1.  Sure, should I use 13 or like 98? Or what do you prefer? 
2. I didn't think of that - i will fix
3. Yeah I kinda forgot to add that, I was actually going to write to a temp file before overwriting original script.  I think i will do both now.
4. Once all is sorted I will create an issue...

**Comment by causefx** [comment]
This PR fixes #99 - Let me know if you need any other changes

**Comment by ChuckPa** [comment]
Almost .

How about `88`  (rhymes with update) 
and please check the destination is writable before the download,  error if not
final message if update successful (with chmod applied)

This way,  they are completely informed as to progress

**Comment by causefx** [comment]
The writable check is performed before the actual download, it just happens to be in the download function...

this is done before the curl...
```
    # Check if script path is writable
    if [ ! -w "$ScriptWorkingDirectory" ]; then
      Output "Script path is not writable."
      exit 2
    fi
```

I was going to move all the checks into that method for better readability.  I can move it out if you really want it out...

**Comment by causefx** [comment]
updated `98` to `88`

**Comment by ChuckPa** [comment]
One more change please.

To be consistent with the rest of the functions,   Don't abruptly exit if they can't update.  Let them decide that.

**Comment by causefx** [comment]
All completed for ya... Thanks!

**Comment by ChuckPa** [comment]
Looks great.

Please squash the interim commits into 1 commit,   fix commit message and change comment to "Add update check with installation to DBRepair"  

Sound good?

**Comment by causefx** [comment]
i believe you are the only that squash on the repo.

**Comment by ChuckPa** [comment]
Corect but you squash before the actual PR

**Pull request closed without merging**
