### PR TITLE
Fix HOTIO with backwards compatibility 

### PR DESCRIPTION
**Pull request by causefx**

### CODE REVIEW

**Comment by causefx** [comment]
Pertains to #92 & #94 - Lemme know if you need anything

**Comment by sittingmongoose** [comment]
Pathing for Hotio was wrong in the regular release, this fixed it for me.

**Review by ChuckPa — CHANGES_REQUESTED** [review]
I need more than pathnames and a find to go on.
This approach makes positioning in the detection positionally dependent.
This needs better.

What can we 'grep' for which is guaranteed ?

**Comment by causefx** [comment]
Not sure, all I can see is he changed the location from `/app/usr/lib/plexmediaserver` to `/usr/lib/plexmediaserver` while still keeping the project at `/config` so we are still checking for the project just like before...  

So, with that, I added the checking for the original path and at the same time checking for the new path...  Whichever one it finds it then uses that path for the `Plex SQLite` file.

Then since he changed the name of the folder for the service, we also check both paths again and use that result for the Stand and Stop commands...

I'll check it there are any identifiers in his container vs others, but I don't have that much motivation to put much effort into it at the moment...

**Comment by ChuckPa** [comment]
> Not sure, all I can see is he changed the location from /app/usr/lib/plexmediaserver to /usr/lib/plexmediaserver while still keeping the project at /config so we are still checking for the project just like before...

There are multiple containers which use `/usr/lib/plexmediaserver`.   We cannot rely on that for identification.
(conflicts with  5-6 (?) other containers.  It does conflict with Plex official.

**Comment by causefx** [comment]
If you are that worried about it swap the if statements for HOTIO and `[ -d "/config/Library/Application Support" ]` so you catch all `normal` containers first and leave the last two checks for HOTIO and binhex...

**Comment by ChuckPa** [comment]
I just came up with an idea and ask for input.
Would any of these be unique enough to guarantee  a `hotio` container ?

If so.  then we can safely search for the app directory.

```
root@hotioplex:/# grep -ir hotio .
./etc/group:users:x:100:hotio
./etc/group:hotio:x:1000:
./etc/group:video3355:x:109:hotio
./etc/gshadow:users:*::hotio
./etc/gshadow:hotio:!::
./etc/gshadow:video3355:!::hotio
./etc/hostname:hotioplex
./etc/passwd:hotio:x:1000:1000::/config:/bin/false
./etc/shadow:hotio:!:19604:0:99999:7:::
./etc/subgid:hotio:100000:65536
./etc/subuid:hotio:100000:65536
./etc/s6-overlay/s6-rc.d/init-setup/run:    usermod -d "/tmp/temphome" hotio
./etc/s6-overlay/s6-rc.d/init-setup/run:    usermod -o -u "${PUID}" hotio
./etc/s6-overlay/s6-rc.d/init-setup/run:    usermod -d "${CONFIG_DIR}" hotio
./etc/s6-overlay/s6-rc.d/init-setup/run:    groupmod -o -g "${PGID}" hotio
./etc/s6-overlay/s6-rc.d/init-setup/run:chown hotio:hotio "${CONFIG_DIR}"
./etc/s6-overlay/s6-rc.d/init-setup/run:chown hotio:hotio "/transcode"
./etc/s6-overlay/s6-rc.d/init-setup/run:    chown -R hotio:hotio "$(dirname "${prefFile}")"
./etc/s6-overlay/s6-rc.d/init-setup/run:    # If the user hotio isn't a member of the group, add him
./etc/s6-overlay/s6-rc.d/init-setup/run:    getent group "${DEVICE_GROUP_NAME}" | grep -q hotio || usermod -a -G "${DEVICE_GROUP_NAME}" hotio
./etc/s6-overlay/s6-rc.d/service-plex/run:PLEX_MEDIA_SERVER_INFO_DEVICE="Docker Container (hotio)"      && export PLEX_MEDIA_SERVER_INFO_DEVICE
./etc/s6-overlay/s6-rc.d/service-plex/run:exec s6-setuidgid hotio "/usr/lib/plexmediaserver/Plex Media Server"
./etc/passwd-:hotio:x:1000:1000::/tmp/temphome:/bin/false
./etc/group-:users:x:100:hotio
./etc/group-:hotio:x:1000:
./etc/gshadow-:users:*::hotio
./etc/gshadow-:hotio:!::
```

**Comment by causefx** [comment]
i can look at the image build and see what is there but i would assume yes.

**Comment by ChuckPa** [comment]
Thank you!   

Having authoritative info is best.

**Comment by causefx** [comment]
Please check the first if statement now, it uses that path as it will still support backward compatibility for the older hotio image.

**Review by ChuckPa — APPROVED** [review]

**Pull request merged**
