### PR TITLE
Add Powershell Script

### PR DESCRIPTION
**Pull request by fscorrupt**
Made a Powershell Script from your .bat File.

image

### CODE REVIEW

**Review by ChuckPa — CHANGES_REQUESTED** [review]
Looks really good for first shot:

If Plex was running and was stopped,  where does the code restart it ?

Are you planning on adding the menu system loop?  
If so,  would you like to hold back on the Pull until you've got it closer to final?
(other than the interaction to stop plex,  how does this differ from the BAT file?)

Would you also mind doing:

1. Open an issue:  "Add Windows powershell version" 
     - Label:  Enhancement
     
 2.  Squash your commits into a single commit and edit the final commit message
 
3.   Decouple the PR from my work with the 'Contributing' guidelines.    
      - update your PR per the contributions guidelines.

**Comment by fscorrupt** [comment]
Hey, thanks.
currently it does not really differ from the BAT.

i just added the ability to identify plex install and query for the required paths + verify if those are present.

and the pms stop/start part. (Start happens on #232)

i can have a look at your sh and make the same experience for the ps1 version, then i think it would be better to close this PR, and i will make one when i polished/finished everything!

**Comment by ChuckPa** [comment]
If you want,   I can grant you permission to work in this repo and have your work on your own branch.
Doing so will allow easier management for both of us.

I use branch naming:     `chuckpa/branch-reason`

**Comment by fscorrupt** [comment]
That would be great, and would really make everything easier!

**Comment by ChuckPa** [comment]
All work to be done in branches:      `username/branch-purpose`

Pull rebase prior to starting work.     (I hate manually cherry-picking commits back into sequence)

Check invitation.

**Comment by fscorrupt** [comment]
Awesome, Got invitation and created the branch :)

**Comment by ChuckPa** [comment]
Cool.   see it.

Please remember to squash all commits before PR.  
This gives me a single, unified, commit to work with. 
Makes it very easy to back out if we run into problems.

**Pull request closed without merging**
