### PR TITLE
Update DBRepair.sh

### PR DESCRIPTION
**Pull request by Shayne55434**
Added additional start/stop commands for docker

### CODE REVIEW

**Comment by ChuckPa** [comment]
@Shayne55434 

Which container is this for please?

**Review by ChuckPa — CHANGES_REQUESTED** [review]
Please detail which container provider uses this mechanism.

If this isn't one of the existing containers,   additional changed and documentation will be

**Comment by Shayne55434** [comment]
> @Shayne55434 
> 
> Which container is this for please?
> 
> Who provides `legacy-services`?
> 

Image: ghcr.io/dockserver/docker-plex

https://github.com/dockserver/container/tree/master/apps/docker-plex

Truthfully, I'm not fully aware of why it's "legacy-services', but they're ya have it. I know the project largely bases their images on Linuxserver.io, but that's about all I know. That, and the added code works for me.

**Comment by ChuckPa** [comment]
@Shayne55434 

I looked through the entire docker registry.   While there are over 4 pages of Plex variants listed,  this provider is not.

From this,  I conclude the number of installations to be very small and niche.

Unfortunately, for this reason,  coupled with the non-standard control mechanism applied to a LinuxServer base,
I must decline the merge.

**Pull request closed without merging**
