### PR TITLE
bugfix: Hotio check for proper directory to exist for service start/stop

### PR DESCRIPTION
**Pull request by brettpetch**
Fixes an issue that causes Plex service in Hotio container to be unable to start/stop using script.

### CODE REVIEW

**Comment by ChuckPa** [comment]
@brettpetch 

Did I miss one?

**Comment by ChuckPa** [comment]
I've built a container:

This is what I find:
```
root@hotioplex:/config# ls -la /run/service
total 0
drwxr-xr-x 4 root root 123 Sep  4 00:35 .
drwxr-xr-x 1 root root 114 Sep  4 00:35 ..
drwxr-xr-x 4 root root  59 Sep  4 00:35 s6-linux-init-shutdownd
lrwxrwxrwx 1 root root  36 Sep  4 00:35 s6rc-fdholder -> /run/s6-rc/servicedirs/s6rc-fdholder
lrwxrwxrwx 1 root root  42 Sep  4 00:35 s6rc-oneshot-runner -> /run/s6-rc/servicedirs/s6rc-oneshot-runner
drwxr-xr-x 2 root root 164 Sep  4 00:35 .s6-svscan
lrwxrwxrwx 1 root root  35 Sep  4 00:35 service-plex -> /run/s6-rc/servicedirs/service-plex
root@hotioplex:/config#
```

Is this something in transition?

**Comment by ChuckPa** [comment]
Further:

```
    # HOTIO Plex image structure is non-standard (contains symlink which breaks detection)
    if  [ -d "/app/usr/lib/plexmediaserver" ] && [ -d "/config/Plug-in Support" ]; then
      PLEX_SQLITE="/app/usr/lib/plexmediaserver/Plex SQLite"
      AppSuppDir="/config"
      PID_FILE="$AppSuppDir/plexmediaserver.pid"
      DBDIR="$AppSuppDir/Plug-in Support/Databases"
      LOGFILE="$DBDIR/DBRepair.log"
      LOG_TOOL="logger"
      if [ -d /run/service/service-plex ]; then
        HaveStartStop=1
        StartCommand="s6-svc -u /run/service/service-plex"
        StopCommand="s6-svc -d /run/service/service-plex"
      fi

      HostType="HOTIO"
      return 0

```

This is where if falls apart.

```root@hotioplex:/config# ls -la /app
total 4
drwxr-xr-x 1 root root 35 Sep  3 17:48 .
drwxr-xr-x 1 root root 57 Sep  4 00:35 ..
drwxr-xr-x 2 root root 31 Sep  3 17:48 config
-rw-r--r-- 1 root root 22 Sep  3 17:48 version
root@hotioplex:/config# ```

**Comment by ChuckPa** [comment]
Which of these images if official  / what am I looking at ?

1. ghcr.io/hotio/plex
2. cr.hotio.dev/hotio/plex

**Comment by brettpetch** [comment]
ghcr.io/hotio/plex is correct (per their documentation). This is where I track changes from:
https://github.com/hotio/plex/tree/release/root/etc/s6-overlay/s6-rc.d

It may be worth adding 2 checks, one for `service-plex`, another for `plex` to prevent issues.

**Comment by ChuckPa** [comment]
Now integrated into previous PR

**Pull request closed without merging**
