### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CLHatch**
"Logfile" is "Option 8", not "Option 7".  I'm guessing you added an option after you wrote the "Typical Usage" section and missed updating it.

### CODE REVIEW

**Review by ChuckPa — APPROVED** [review]
Approved.

Thank you for catching this.  While it needed fixing,  I would hope anyone using this tool would be have the common sense to look at the command name and not the number.

Speaking of command name,  I'm considering changing the parser to get rid of numbers.  
It'll be a big effort and all doc will need overhaul.   Thoughts?   I'll open a new GHI

I'll merge this commit.

**Comment by CLHatch** [comment]
> Approved.
> 
> Thank you for catching this. While it needed fixing, I would hope anyone using this tool would be have the common sense to look at the command name and not the number.
> 
> Speaking of command name, I'm considering changing the parser to get rid of numbers. It'll be a big effort and all doc will need overhaul. Thoughts? I'll open a new GHI
> 
> I'll merge this commit.

Yeah, I didn't notice the error at first, not even realizing the error, because "common sense" kicked in and converted it in my brain as I read it. :-D

Yeah, probably a good idea, doing away with the numbers, seeing as you have run out of single digit numbers to use (unless you use 0).  I would suggest maybe the "standard" of for the command-line, single letter "short" options and single word "long" options such as `-r` or `--repair`.  And for the "interactive" mode, possibly use the single letter ones as the keyboard options, so `R` would be `repair`?

**Comment by ChuckPa** [comment]
Yes,  I'm looking at the full lower/upper minimal match thing.
It should be easy enough to pick the best match index from array of keywords.

**Comment by CLHatch** [comment]
For the command-line options (and possibly even for the "interactive" menu), it might be an idea to include "All In One" options that do some of the common "multiple commands" that people would do, say one option that does the equiv of the current `./DBRepair.sh 1 4 3 9`?  Not sure what other common sequences that people might want to do, but that one definitely comes to mind that could warrant a single option.

**Pull request merged**
